---
- include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_distribution }}.yml'
    - '{{ ansible_os_family }}.yml'

- name: Ensure keepalived and its dependency are installed
  package:
    name: "{{ keepalived_packages }}"
    state: present
  when: keepalived_install == True

- name: Ensure keepalived_script user is created
  user:
    name: keepalived_script
    shell: /bin/nologin
    create_home: no

- name: Ensure keepalived.conf is installed
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Ensure keepalived is started
  service:
    name: keepalived
    state: started
    enabled: yes
