---
- name: Ensure keepalived is installed
  package:
    name: keepalived
    state: present
  when: keepalived_install == True

- name: Ensure keepalived.conf is installed
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Ensure keepalived is started
  service:
    name: keepalived
    state: started
    enabled: yes
